apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/user
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: APPLICATION_PORT
              value: "3000"
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: port
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_SYNCHRONIZE
              value: "true"
            - name: MYSQL_POOL_SIZE
              value: "10"
            - name: MYSQL_LOGGING
              value: "true"
            - name: MYSQL_ENTITIES
              value: dist/**/infrastructure/**/*.entity.js
            - name: MYSQL_MAX_QUERY_EXECUTION_TIME
              value: "10000"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
