apiVersion: v1
kind: Secret
metadata:
  name: super-secret
type: Opaque
data:
  user: YWRtaW5pc3RyYXRvcg==
  pass: RDEwc0RlbDIwMjQkIw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: user
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: pass
