version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: on-failure
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
