apiVersion: v1
kind: Pod
metadata:
  name: server-nginx
spec:
  containers:
    - name: server-nginx
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: devops
spec:
  containers:
    - name: devops
      image: sonarqube:latest
