apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-uat
  labels:
    env: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    env: prd
