
### Insert
POST http://localhost:3000/product/v1
Content-Type: application/json

{
    "name": "Product 6",
    "price": 100,
    "description": "Product 1 description",
    "image": "https://picsum.photos/200/300"
}

### List one
GET http://localhost:3000/product/v1/f82502ce-69f3-4a56-b28a-f0e0a584392d

### List all
GET http://localhost:3000/product/v1

### Update
PUT http://localhost:3000/product/v1/f82502ce-69f3-4a56-b28a-f0e0a584392d
Content-Type: application/json

{
    "name": "Product 100",
    "price": 200
}

### Delete
DELETE http://localhost:3000/product/v1/b0092517-8fdc-4c3c-b0a1-8ddc6c0f2a37

### List by page
GET http://localhost:3000/product/v1/page/?page=1&pageSize=3