apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
